### ISSUE TITLE
Add some extra information for the InvoiceMailable.

### ISSUE THREAD

**Issue by wotta** [tomirons/tuxedo#1]
You may need to add some extra line for the information about payment stuff.
Please contact me if you need a better idea on what I mean.

**Comment by tomirons** [comment]
I've added `subtotal`, `tax`, and `shipping` into the invoices in `1.0.2`. I hope that's good enough. This is supposed to be a simple package, let's try to keep it that way. You're more than welcome to make a PR with more options, I won't stop anyone from doing that. 👍
