### ISSUE TITLE
Is your package only for v5.4?

### ISSUE THREAD

**Issue by eescalante** [tomirons/tuxedo#17]
I'm want to switch my production project to 5.4 yet, but was looking for this mailable solution but i'm using v5.3. I know that markdown is not available in my version but i just want to have MailMessage functionality on Mailable object, is that possible with your soluction?

Best regards
GP

**Comment by tomirons** [comment]
Unfortunately it will only work for 5.4 and above, only because it requires the `Markdown` classes.
