### ISSUE TITLE
any suggestion for logging all this mail activity?

### ISSUE THREAD

**Issue by vesper8** [tomirons/tuxedo#18]
Hi there! I really like your package and will start using it right away.

I was wondering however if you have any suggestions for me, I would like to have a detailed "mail log" of all this activity.

I am thinking of simply using https://github.com/spatie/laravel-activitylog. But I wouldn't have minded something similar to that but exclusively for tracking emails.

I would like to created queue-able emails.. see at what time they were queued, at what time they were sent.. to whom they were sent.. and some other details. Anything like that already exist?

**Comment by tomirons** [comment]
You're more than welcome to use that package in conjunction with tuxedo.

 If you're wanting to log all mail sent from your application, I would create a listener for either `Illuminate\Mail\Events\MessageSending` or `Illuminate\Mail\Events\MessageSent` and use the activity package that way.
