### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by EazyServer** [tomirons/tuxedo#7]
Hi there,

is it possible to reduce the minimum php compatibility to 5.6 on composer?

**Comment by tomirons** [comment]
I'm in the process of putting together some tests, after this is done it should work with 5.6.

**Comment by tomirons** [comment]
@EazyServer I've gotten the tests done and I've changed the required version to **5.6.4**.

**Comment by EazyServer** [comment]
Thanks very much
